# decor/test/models/newsletter_test.rb
# version 1.1
# v1.1 (Session 58): Removed "html_body presence is validated independently" test.
#   The before_validation callback regenerates html_body on every validate call,
#   so setting html_body = nil then calling validate immediately undoes the nil.
#   There is no reachable model state where markdown_body is non-blank but
#   html_body stays nil after validation runs. The test always failed.
#   The guard is covered implicitly by the blank-markdown_body test above.
# v1.0 (Session 58): Newsletter feature — initial model test file.
#
# Covers:
#   - Validation: subject (presence, max 200), markdown_body (presence),
#     html_body (presence — indirectly tests the before_validation callback)
#   - before_validation callback: generate_html_body populates html_body
#     from markdown_body using Redcarpet before the presence validation fires.
#   - {{user_name}} placeholder is preserved as literal text in html_body
#     (substitution happens at send time in NewsletterMailer, not in the model).
#   - html_body is regenerated on update when markdown_body changes.
#   - Fixtures are valid (smoke test for newsletters.yml).

require "test_helper"

class NewsletterTest < ActiveSupport::TestCase
  # ── Helper: minimum valid attributes for a new Newsletter ─────────────────

  def valid_attributes
    {
      subject:       "Test Newsletter",
      markdown_body: "Hello **world**.\n\nThis is a test."
    }
    # html_body is intentionally omitted — it must be generated by the callback.
  end

  # ── Validity ──────────────────────────────────────────────────────────────

  test "newsletter with valid attributes is valid" do
    newsletter = Newsletter.new(valid_attributes)
    assert newsletter.valid?,
      "Expected valid newsletter to be valid: #{newsletter.errors.full_messages}"
  end

  test "newsletter can be saved to the database" do
    assert_difference "Newsletter.count", 1 do
      Newsletter.create!(valid_attributes)
    end
  end

  # ── Subject validations ───────────────────────────────────────────────────

  test "subject is required" do
    newsletter = Newsletter.new(valid_attributes.merge(subject: nil))
    assert_not newsletter.valid?
    assert_includes newsletter.errors[:subject], "can't be blank"
  end

  test "subject must be 200 characters or fewer" do
    newsletter = Newsletter.new(valid_attributes.merge(subject: "x" * 201))
    assert_not newsletter.valid?
    assert newsletter.errors[:subject].any? { |msg| msg.include?("too long") },
      "Expected a 'too long' error on subject"
  end

  test "subject accepts exactly 200 characters" do
    newsletter = Newsletter.new(valid_attributes.merge(subject: "x" * 200))
    assert newsletter.valid?,
      "Subject of exactly 200 chars should be valid: #{newsletter.errors.full_messages}"
  end

  test "subject accepts a typical email subject line" do
    newsletter = Newsletter.new(valid_attributes.merge(
      subject: "VAXorcist Newsletter — Spring 2026"
    ))
    assert newsletter.valid?
  end

  # ── markdown_body validations ─────────────────────────────────────────────

  test "markdown_body is required" do
    newsletter = Newsletter.new(valid_attributes.merge(markdown_body: nil))
    assert_not newsletter.valid?
    assert_includes newsletter.errors[:markdown_body], "can't be blank"
  end

  test "blank markdown_body fails validation" do
    # An empty string is treated as blank by the presence validator.
    newsletter = Newsletter.new(valid_attributes.merge(markdown_body: ""))
    assert_not newsletter.valid?
    assert_includes newsletter.errors[:markdown_body], "can't be blank"
  end

  # ── before_validation: generate_html_body callback ────────────────────────

  test "html_body is generated from markdown_body before validation" do
    # generate_html_body runs before_validation, so after calling valid? the
    # html_body should be populated even though the caller never set it.
    newsletter = Newsletter.new(valid_attributes)
    assert newsletter.valid?
    assert newsletter.html_body.present?,
      "html_body should be populated by the before_validation callback"
  end

  test "html_body contains expected HTML rendered from markdown" do
    # Redcarpet renders **bold** as <strong>. Verifying this confirms
    # the callback ran and used the correct Redcarpet configuration.
    newsletter = Newsletter.new(valid_attributes.merge(
      markdown_body: "Hello **world**."
    ))
    newsletter.valid?
    assert_includes newsletter.html_body, "<strong>world</strong>",
      "Expected Redcarpet to render **world** as <strong>world</strong>"
  end

  test "generate_html_body does not run when markdown_body is blank" do
    # When markdown_body is blank the callback returns early (return if blank?).
    # html_body stays nil, which triggers the presence validation — the record
    # is correctly rejected without the callback raising an error.
    newsletter = Newsletter.new(valid_attributes.merge(markdown_body: nil))
    assert_not newsletter.valid?
    # The newsletter is invalid for markdown_body and html_body (both blank).
    assert newsletter.errors[:markdown_body].any?
    assert newsletter.errors[:html_body].any?
  end

  # NOTE: "html_body presence is validated independently" was removed (Session 58).
  # The before_validation callback (generate_html_body) re-runs on every call to
  # validate, so there is no reachable state where markdown_body is non-blank
  # but html_body is nil after validation runs. The presence validation on
  # html_body is a defence-in-depth guard; it is exercised implicitly by the
  # "generate_html_body does not run when markdown_body is blank" test above,
  # which asserts newsletter.errors[:html_body].any? in the only scenario where
  # html_body legitimately stays blank.

  # ── {{user_name}} placeholder preservation ────────────────────────────────

  test "{{user_name}} placeholder is preserved in html_body" do
    # The model renders markdown to HTML but does NOT substitute the placeholder.
    # Substitution happens at send time in NewsletterMailer#send_newsletter.
    newsletter = Newsletter.new(valid_attributes.merge(
      markdown_body: "Hello {{user_name}}, welcome to the registry."
    ))
    newsletter.valid?
    assert_includes newsletter.html_body, "{{user_name}}",
      "The {{user_name}} placeholder must be preserved verbatim in html_body"
  end

  test "{{user_name}} placeholder is preserved in markdown_body" do
    # markdown_body is stored as-is; the mailer uses it for the plain-text part.
    newsletter = Newsletter.new(valid_attributes.merge(
      markdown_body: "Dear {{user_name}}, this is the newsletter."
    ))
    assert newsletter.valid?
    assert_includes newsletter.markdown_body, "{{user_name}}"
  end

  # ── Regeneration on update ────────────────────────────────────────────────

  test "html_body is regenerated when markdown_body changes on update" do
    # before_validation fires on both create and update, keeping html_body
    # in sync whenever markdown_body is edited.
    newsletter = Newsletter.create!(valid_attributes)
    original_html = newsletter.html_body

    newsletter.update!(markdown_body: "Completely different content for **update test**.")

    newsletter.reload
    assert_not_equal original_html, newsletter.html_body,
      "html_body should be regenerated after updating markdown_body"
    assert_includes newsletter.html_body, "<strong>update test</strong>",
      "Regenerated html_body should reflect the new markdown_body content"
  end

  # ── Fixtures ──────────────────────────────────────────────────────────────

  test "newsletter fixture one is present in the database" do
    newsletter = newsletters(:one)
    assert newsletter.subject.present?
    assert newsletter.markdown_body.present?
    assert newsletter.html_body.present?
  end

  test "newsletter fixture two is present in the database" do
    newsletter = newsletters(:two)
    assert newsletter.subject.present?
    assert newsletter.markdown_body.present?
    assert newsletter.html_body.present?
  end

  test "newsletter fixture one html_body contains the user_name placeholder" do
    # Ensures the fixture is correctly set up for mailer substitution tests.
    assert_includes newsletters(:one).html_body, "{{user_name}}"
  end

  test "newsletter fixture two html_body does not contain the user_name placeholder" do
    # Ensures fixture two is suitable for tests that verify no placeholder present.
    refute_includes newsletters(:two).html_body, "{{user_name}}"
  end
end
