# decor/app/helpers/application_helper.rb
# version 1.2
# v1.1 (Session 18): Added render_markdown helper — converts a markdown string to
#   safe HTML using the redcarpet gem. Used by the site text show page (README etc.).
#   Standard markdown links work: [text](/path) for internal, [text](https://...) for
#   external. The renderer allows HTML passthrough since only admins supply content.
# v1.2 (Session 20): Added with_toc_data: true to the HTML renderer so that headings
#   receive id= attributes. This enables in-page anchor links, e.g. [Section](#section),
#   which is required for a working Table of Contents inside a markdown page.
#   Anchor ID format (generated by redcarpet): lowercase, spaces → hyphens, punctuation stripped.
#   Example: ## Text Formatting → id="text-formatting" → link as [Text Formatting](#text-formatting)

module ApplicationHelper
  def visible_field(owner, field)
    visibility = owner.send("#{field}_visibility")

    visible = case visibility
    when "public" then true
    when "members_only" then logged_in?
    when "private" then Current.owner == owner
    else false
    end

    return nil unless visible

    if block_given?
      yield
    else
      owner.send(field)
    end
  end

  def empty_state(message)
    tag.div message, class: "col-span-full flex items-center justify-center min-h-32 p-4 bg-stone-100 text-stone-500 text-sm"
  end

  # Renders a markdown string as HTML, marked safe for output in views.
  # Uses redcarpet with a standard set of extensions:
  #   - tables, fenced_code_blocks, autolink, strikethrough, superscript
  #   - hard_wrap: converts single newlines to <br> (friendlier for plain text authors)
  # Only admins can supply content — HTML passthrough is intentionally allowed.
  # Returns an empty string when text is blank.
  #
  # with_toc_data: true — adds id= attributes to all heading elements so that
  #   anchor links like [Section Title](#section-title) work within the page.
  def render_markdown(text)
    return "".html_safe if text.blank?

    renderer = Redcarpet::Render::HTML.new(
      with_toc_data:   true,   # adds id= to headings → enables in-page anchor links
      hard_wrap:       true,   # single newline → <br>
      no_images:       false,  # allow image tags from markdown
      no_links:        false,  # allow link tags
      safe_links_only: true    # reject non-http(s) link schemes (javascript: etc.)
    )

    markdown = Redcarpet::Markdown.new(
      renderer,
      tables:             true,
      fenced_code_blocks: true,
      autolink:           true,
      strikethrough:      true,
      superscript:        true,
      no_intra_emphasis:  true  # prevents foo_bar_baz from italicising "bar"
    )

    markdown.render(text).html_safe
  end
end
