# decor/db/migrate/20260430000100_create_newsletters.rb
# version 1.0
# Session 56: Newsletter feature — creates the newsletters table.
#
# Columns:
#   subject       VARCHAR(200) NOT NULL — email subject line shown to recipients.
#   markdown_body TEXT         NOT NULL — raw markdown as uploaded by the admin.
#   html_body     TEXT         NOT NULL — HTML rendered from markdown_body;
#                                         generated by Newsletter model before_save.
#                                         {{user_name}} placeholders in html_body are
#                                         substituted per-recipient at send time.
#
# TEXT approved by user (Session 56): newsletter body is free-form long content;
# TEXT is the appropriate column type for both markdown_body and html_body.
#
# subject uses limit: 200 (maps to VARCHAR(200) in the schema).
# Note: SQLite does not enforce VARCHAR length at runtime without a CHECK constraint.
# A model validation covers this at the application level (see newsletter.rb).

class CreateNewsletters < ActiveRecord::Migration[8.1]
  def change
    create_table :newsletters do |t|
      # Subject line for the email — shown in recipient's inbox.
      t.string  :subject,       null: false, limit: 200

      # Raw markdown content as uploaded. Preserved so the newsletter can be
      # re-rendered if the conversion logic changes in a future release.
      t.text    :markdown_body, null: false

      # Pre-rendered HTML — generated from markdown_body on save.
      # {{user_name}} placeholders remain in this column; they are replaced
      # with the actual recipient user_name at send time by NewsletterMailer.
      t.text    :html_body,     null: false

      t.timestamps
    end
  end
end
